jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug AWS credentials
        run: |
          echo "AWS Access Key ID: ${{ secrets.ACCESS_KEY }}"
          echo "AWS Secret Access Key: ${{ secrets.SECRET_KEY }}"
          echo "AWS Region: ${{ secrets.AMS_REGION }}"
          echo "S3 Bucket Name: ${{ secrets.S3_BUCKET_NAME }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ secrets.AMS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: 586794461410.dkr.ecr.${{ secrets.AMS_REGION }}.amazonaws.com
          ECR_REPOSITORY: website-static
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "S3 Bucket Name: $S3_BUCKET_NAME"