# Use a lightweight web server image
FROM nginx:alpine

# Copy your website files to the Nginx server's default directory
COPY . /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]